### ISSUE TITLE
Error while downloading 

### ISSUE THREAD

**Issue by F-yol** [Ryukotsuki/Poke-Manager#1]
When downloading the Archetype Counter I get a message that says: An error occurred during download: float division by zero.

This is what appears in the space at the bottom:
"You are using the latest version.
An error occurred during download: float division by zero
Download complete."

![image](https://github.com/Ryukotsuki/PokeMMO-Manager/assets/160557734/4fface55-5ec4-430f-aaa8-118e41c1cd27)

**Comment by yaboifrost** [comment]
Try the newest version

**Comment by Ryukotsuki** [comment]
> When downloading the Archetype Counter I get a message that says: An error occurred during download: float division by zero.
> 
> This is what appears in the space at the bottom: "You are using the latest version. An error occurred during download: float division by zero Download complete."
> 
> ![image](https://private-user-images.githubusercontent.com/160557734/310058990-4fface55-5ec4-430f-aaa8-118e41c1cd27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTQ4MDcsIm5iZiI6MTcwOTc5NDUwNywicGF0aCI6Ii8xNjA1NTc3MzQvMzEwMDU4OTkwLTRmZmFjZTU1LTVlYzQtNDMwZi1hYWE4LTExOGU0MWMxY2QyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNjU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWU5NzE4YTM2NjJhNjdkODgzNmNmMWRlN2U3NzZiY2RjN2QwNGU0OTAwNDNkOGNiZWYzMzAyMDg1NDJkMzMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rXu8JI33y8GOnN6HtFc3NJJ1S6qHw9_RkvMjiPRCQrE)

Fixed in latest version 7.0.0

**Comment by F-yol** [comment]
The problem is fixed, but fyi, Window now sees the program as a trojan, and delete it at random!

**Comment by Ryukotsuki** [comment]
> The problem is fixed, but fyi, Window now sees the program as a trojan, and delete it at random!

This is an issue within Python when converting files to an exe using PyInstaller sometimes they will automatically be flagged by an antivirus nothing I can do about it maybe my next release won't get flagged join the discord i have instructions for the program being flagged by windows https://discord.gg/HdfjKbPNc9.
